export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
export const INCIDENTS_REQUEST = 'INCIDENT_REQUEST';
export const INCIDENTS_SUCCESS = 'INCIDENT_SUCCESS';
export const INCIDENTS_FAILURE = 'INCIDENT_FAILURE';
